#!/usr/bin/env bash
# Turn secrets.env into nix/secrets.nix.
#
# secrets.env is gitignored and must stay out of git and out of any image that
# could reach a registry. nix/secrets.nix is gitignored for the same reason.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${1:-$repo_root/secrets.env}"
out="$repo_root/nix/secrets.nix"

[[ -r $env_file ]] || { echo "no such secrets file: $env_file" >&2; exit 1; }

# shellcheck disable=SC1090
set -a; source "$env_file"; set +a

for v in RPI_HOSTNAME RPI_USER RPI_PASSWORD RPI_WIFI_SSID RPI_WIFI_PSK; do
    [[ -n ${!v:-} ]] || { echo "$v is unset in $env_file" >&2; exit 1; }
done

esc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\${/\\${/g'; }

umask 077
cat > "$out" <<EOF
# Generated by nix/mksecrets.sh from $(basename "$env_file"). Not in git.
{
  hostname = "$(esc "$RPI_HOSTNAME")";
  user = "$(esc "$RPI_USER")";
  password = "$(esc "$RPI_PASSWORD")";
  wifiSsid = "$(esc "$RPI_WIFI_SSID")";
  wifiPsk = "$(esc "$RPI_WIFI_PSK")";
}
EOF
echo "wrote $out (mode $(stat -c %a "$out"))"
